# Generated by Django 5.0.6 on 2024-07-10 15:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0021_alter_billingmodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 7, 10))]),
        ),
    ]
