# Generated by Django 5.0.3 on 2024-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_date_modified_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Hotel Manager'), ('customer_service', 'Customer Service')], max_length=20),
        ),
    ]
