# Generated by Django 5.0.3 on 2024-03-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Hotel Manager'), ('customer_service', 'Customer Service'), ('customer_service_supervisor', 'Customer Service Supervisor')], max_length=30),
        ),
    ]
