# Generated by Django 5.0.3 on 2024-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Hotel Manager'), ('customer_service', 'Customer Service'), ('team_lead', 'Customer Service Team Lead')], max_length=30),
        ),
    ]
