# Generated by Django 5.0.3 on 2024-04-02 11:23

import auth_app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_app.managers.UserManager()),
            ],
        ),
    ]
