# Generated by Django 5.0.3 on 2024-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='not set for now', max_length=100),
            preserve_default=False,
        ),
    ]
