# Generated by Django 5.0.3 on 2024-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_user_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
