# Generated by Django 5.0.3 on 2024-03-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('min_advance_booking', models.PositiveIntegerField()),
                ('max_advance_booking', models.PositiveIntegerField()),
                ('hotel_capacity', models.PositiveIntegerField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('hotel_address', models.TextField()),
                ('hotel_phone', models.CharField(max_length=20)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('default_currency', models.CharField(max_length=3)),
                ('room_types', models.JSONField(blank=True, null=True)),
                ('accepted_payment_methods', models.JSONField(blank=True, null=True)),
                ('hotel_amenities', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('notification_settings', models.JSONField(blank=True, null=True)),
                ('user_preferences', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
