# Generated by Django 5.0.3 on 2024-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='check_in_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='check_out_time',
            field=models.CharField(max_length=100),
        ),
    ]
