# Generated by Django 5.0.3 on 2024-05-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_hotelsettingsmodel_check_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='hotelsettingsmodel',
            name='manager',
        ),
    ]
