# Generated by Django 5.0.3 on 2024-03-22 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_hotelsettings_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='AgentModel',
        ),
        migrations.RenameModel(
            old_name='AgentRole',
            new_name='AgentRoleModel',
        ),
        migrations.RenameModel(
            old_name='ContactChannel',
            new_name='ContactChannelModel',
        ),
        migrations.RenameModel(
            old_name='HotelSettings',
            new_name='HotelSettingsModel',
        ),
        migrations.RenameModel(
            old_name='Reservation',
            new_name='ReservationModel',
        ),
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSettingsModel',
        ),
    ]
