# Generated by Django 5.0.3 on 2024-04-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_rename_agent_agentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='ReservationModel',
        ),
    ]
