# Generated by Django 5.0.3 on 2024-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_hotelsettingsmodel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='check_out_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='number_of_rooms',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
