# Generated by Django 5.0.3 on 2024-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_alter_hotelsettingsmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettingsmodel',
            options={'verbose_name_plural': 'User Settings'},
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False, help_text='Whether the user has enabled dark mode'),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='notification_settings',
            field=models.JSONField(blank=True, help_text='JSON field to store notification settings', null=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettingsmodel',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
