# Generated by Django 5.0.3 on 2024-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_alter_usersettingsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingsmodel',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
