# Generated by Django 5.0.3 on 2024-05-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_alter_usersettingsmodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettingsmodel',
            options={},
        ),
    ]
