# Generated by Django 5.0.3 on 2024-05-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_alter_usersettingsmodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelsettingsmodel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_field_on_hotel_setting', to=settings.AUTH_USER_MODEL),
        ),
    ]
