# Generated by Django 5.0.3 on 2024-04-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='customer_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='last_name',
            field=models.CharField(default='lost', max_length=100),
            preserve_default=False,
        ),
    ]
