# Generated by Django 5.0.3 on 2024-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reservationmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('hotel_location', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='specia_requests',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=100),
        ),
    ]
