# Generated by Django 5.0.3 on 2024-04-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_waitlistmember_reservationmodel_specia_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistmember',
            old_name='customer_email',
            new_name='waiter_email',
        ),
        migrations.RenameField(
            model_name='waitlistmember',
            old_name='name',
            new_name='waiter_name',
        ),
        migrations.RenameField(
            model_name='waitlistmember',
            old_name='customer_phone',
            new_name='waiter_phone',
        ),
    ]
