# Generated by Django 5.0.3 on 2024-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_customer_email_waitlistmember_waiter_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistmember',
            old_name='hotel_location',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='waitlistmember',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='waitlistmember',
            name='waiter_email',
        ),
        migrations.RemoveField(
            model_name='waitlistmember',
            name='waiter_name',
        ),
        migrations.RemoveField(
            model_name='waitlistmember',
            name='waiter_phone',
        ),
        migrations.AddField(
            model_name='waitlistmember',
            name='company_name',
            field=models.EmailField(default='non existent', max_length=100),
            preserve_default=False,
        ),
    ]
