# Generated by Django 5.0.3 on 2024-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_hotel_location_waitlistmember_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='specia_requests',
            new_name='special_requests',
        ),
        migrations.AlterField(
            model_name='waitlistmember',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
