# Generated by Django 5.0.6 on 2024-07-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=300, unique=True)),
                ('phone_number', models.CharField(max_length=300, unique=True)),
                ('app_secret', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_business_account_id', models.CharField(max_length=300, null=True, unique=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('is_handle_by_human', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appservice.appservice')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(blank=True, choices=[('human', 'human'), ('ai', 'ai')], max_length=20, null=True)),
                ('chatsession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appservice.chatsession')),
            ],
        ),
    ]
